# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Choroid.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1245, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_Thickness = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Thickness.setGeometry(QtCore.QRect(60, 160, 341, 341))
        self.graphicsView_Thickness.setObjectName("graphicsView_Thickness")
        self.graphicsView_Vessel = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Vessel.setGeometry(QtCore.QRect(440, 160, 341, 341))
        self.graphicsView_Vessel.setObjectName("graphicsView_Vessel")
        self.graphicsView_CVI = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_CVI.setGeometry(QtCore.QRect(820, 160, 341, 341))
        self.graphicsView_CVI.setObjectName("graphicsView_CVI")
        self.lineEdit_cvi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cvi.setEnabled(True)
        self.lineEdit_cvi.setGeometry(QtCore.QRect(90, 570, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_cvi.setFont(font)
        self.lineEdit_cvi.setText("")
        self.lineEdit_cvi.setObjectName("lineEdit_cvi")
        self.lineEdit_mct = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mct.setEnabled(True)
        self.lineEdit_mct.setGeometry(QtCore.QRect(290, 570, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_mct.setFont(font)
        self.lineEdit_mct.setText("")
        self.lineEdit_mct.setObjectName("lineEdit_mct")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 570, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 570, 47, 13))
        self.label_2.setObjectName("label_2")
        self.pushButton_Run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Run.setGeometry(QtCore.QRect(630, 580, 101, 23))
        self.pushButton_Run.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 130, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(970, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenFile.setGeometry(QtCore.QRect(280, 60, 76, 23))
        self.pushButton_OpenFile.setObjectName("pushButton_OpenFile")
        self.lineEdit_OpenPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OpenPath.setGeometry(QtCore.QRect(60, 60, 211, 21))
        self.lineEdit_OpenPath.setText("")
        self.lineEdit_OpenPath.setObjectName("lineEdit_OpenPath")
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setGeometry(QtCore.QRect(760, 580, 101, 23))
        self.pushButton_Save.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 530, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1245, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CVI"))
        self.label_2.setText(_translate("MainWindow", "MCT"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run"))
        self.label_3.setText(_translate("MainWindow", "Thickness"))
        self.label_4.setText(_translate("MainWindow", "Vessel"))
        self.label_5.setText(_translate("MainWindow", "CVI"))
        self.pushButton_OpenFile.setText(_translate("MainWindow", "Open Folder"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "Choriod Quantificaiton v1.0"))
        self.label_7.setText(_translate("MainWindow", "Results"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
