# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Regi.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1249, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_Ref = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Ref.setGeometry(QtCore.QRect(460, 40, 351, 351))
        self.graphicsView_Ref.setObjectName("graphicsView_Ref")
        self.graphicsView_Mov = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Mov.setGeometry(QtCore.QRect(830, 40, 351, 351))
        self.graphicsView_Mov.setObjectName("graphicsView_Mov")
        self.graphicsView_Ave = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Ave.setGeometry(QtCore.QRect(460, 460, 351, 351))
        self.graphicsView_Ave.setObjectName("graphicsView_Ave")
        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Title.setGeometry(QtCore.QRect(10, 0, 261, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.label_Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Title_2.setGeometry(QtCore.QRect(300, 0, 129, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_Title_2.setFont(font)
        self.label_Title_2.setObjectName("label_Title_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 290, 430, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.pushButton_LoadStruMov = QtWidgets.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_LoadStruMov.setFont(font)
        self.pushButton_LoadStruMov.setObjectName("pushButton_LoadStruMov")
        self.gridLayout_4.addWidget(self.pushButton_LoadStruMov, 3, 0, 1, 1)
        self.pushButton_LoadSeg = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_LoadSeg.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_LoadSeg.setFont(font)
        self.pushButton_LoadSeg.setObjectName("pushButton_LoadSeg")
        self.gridLayout_4.addWidget(self.pushButton_LoadSeg, 1, 1, 1, 1)
        self.pushButton_LoadFlow_2 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_LoadFlow_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_LoadFlow_2.setFont(font)
        self.pushButton_LoadFlow_2.setObjectName("pushButton_LoadFlow_2")
        self.gridLayout_4.addWidget(self.pushButton_LoadFlow_2, 3, 1, 1, 1)
        self.pushButton_LoadStruRef = QtWidgets.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_LoadStruRef.setFont(font)
        self.pushButton_LoadStruRef.setObjectName("pushButton_LoadStruRef")
        self.gridLayout_4.addWidget(self.pushButton_LoadStruRef, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.pushButton_Run = QtWidgets.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_Run.setFlat(False)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.gridLayout_4.addWidget(self.pushButton_Run, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.pushButton_UpdateRule = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_UpdateRule.setObjectName("pushButton_UpdateRule")
        self.gridLayout_3.addWidget(self.pushButton_UpdateRule, 2, 1, 1, 1)
        self.lineEdit_FlowPattern = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_FlowPattern.setObjectName("lineEdit_FlowPattern")
        self.gridLayout_3.addWidget(self.lineEdit_FlowPattern, 1, 1, 1, 1)
        self.listWidget_BatchList = QtWidgets.QListWidget(self.tab_6)
        self.listWidget_BatchList.setObjectName("listWidget_BatchList")
        self.gridLayout_3.addWidget(self.listWidget_BatchList, 0, 2, 5, 1)
        self.lineEdit_StruPattern = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_StruPattern.setObjectName("lineEdit_StruPattern")
        self.gridLayout_3.addWidget(self.lineEdit_StruPattern, 0, 1, 1, 1)
        self.pushButton_RunSingle = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_RunSingle.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RunSingle.setFont(font)
        self.pushButton_RunSingle.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_RunSingle.setObjectName("pushButton_RunSingle")
        self.gridLayout_3.addWidget(self.pushButton_RunSingle, 3, 0, 1, 2)
        self.pushButton_RunBatch = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_RunBatch.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RunBatch.setFont(font)
        self.pushButton_RunBatch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_RunBatch.setMouseTracking(False)
        self.pushButton_RunBatch.setWhatsThis("")
        self.pushButton_RunBatch.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_RunBatch.setObjectName("pushButton_RunBatch")
        self.gridLayout_3.addWidget(self.pushButton_RunBatch, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab_6, "")
        self.lineEdit_OpenPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OpenPath.setGeometry(QtCore.QRect(10, 40, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_OpenPath.setFont(font)
        self.lineEdit_OpenPath.setObjectName("lineEdit_OpenPath")
        self.pushButton_BatchOpen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BatchOpen.setGeometry(QtCore.QRect(320, 40, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_BatchOpen.setFont(font)
        self.pushButton_BatchOpen.setObjectName("pushButton_BatchOpen")
        self.graphicsView_LossAffine = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_LossAffine.setGeometry(QtCore.QRect(1990, 830, 351, 161))
        self.graphicsView_LossAffine.setObjectName("graphicsView_LossAffine")
        self.listWidget_ParaInfo = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_ParaInfo.setGeometry(QtCore.QRect(10, 583, 411, 91))
        self.listWidget_ParaInfo.setObjectName("listWidget_ParaInfo")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ParaInfo.addItem(item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(10, 520, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_log.setGeometry(QtCore.QRect(10, 690, 411, 151))
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(830, 20, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 440, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 230, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.graphicsView_Error = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Error.setGeometry(QtCore.QRect(830, 460, 351, 351))
        self.graphicsView_Error.setObjectName("graphicsView_Error")
        self.horizontalScrollBar_SlowScan = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_SlowScan.setGeometry(QtCore.QRect(830, 400, 351, 17))
        self.horizontalScrollBar_SlowScan.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_SlowScan.setObjectName("horizontalScrollBar_SlowScan")
        self.horizontalScrollBar_FastScan = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_FastScan.setGeometry(QtCore.QRect(470, 400, 341, 17))
        self.horizontalScrollBar_FastScan.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_FastScan.setObjectName("horizontalScrollBar_FastScan")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(10, 550, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 550, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(170, 550, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lcdNumber_SlowScan = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_SlowScan.setGeometry(QtCore.QRect(1100, 10, 79, 23))
        self.lcdNumber_SlowScan.setObjectName("lcdNumber_SlowScan")
        self.lcdNumber_DepthScan = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_DepthScan.setGeometry(QtCore.QRect(730, 430, 75, 23))
        self.lcdNumber_DepthScan.setObjectName("lcdNumber_DepthScan")
        self.lcdNumber_FastScan = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_FastScan.setGeometry(QtCore.QRect(740, 10, 75, 23))
        self.lcdNumber_FastScan.setObjectName("lcdNumber_FastScan")
        self.horizontalScrollBar_FastScan_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_FastScan_2.setGeometry(QtCore.QRect(460, 820, 351, 17))
        self.horizontalScrollBar_FastScan_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_FastScan_2.setObjectName("horizontalScrollBar_FastScan_2")
        self.radioButton_SingleFile = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_SingleFile.setGeometry(QtCore.QRect(30, 130, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_SingleFile.setFont(font)
        self.radioButton_SingleFile.setChecked(False)
        self.radioButton_SingleFile.setObjectName("radioButton_SingleFile")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_SingleFile)
        self.radioButton_MultiFile = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_MultiFile.setGeometry(QtCore.QRect(170, 130, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_MultiFile.setFont(font)
        self.radioButton_MultiFile.setChecked(True)
        self.radioButton_MultiFile.setObjectName("radioButton_MultiFile")
        self.buttonGroup_2.addButton(self.radioButton_MultiFile)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spinBox_ImageGroup = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_ImageGroup.setGeometry(QtCore.QRect(320, 250, 111, 31))
        self.spinBox_ImageGroup.setMinimum(1)
        self.spinBox_ImageGroup.setObjectName("spinBox_ImageGroup")
        self.pushButton_OpenSaveFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenSaveFolder.setGeometry(QtCore.QRect(320, 70, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_OpenSaveFolder.setFont(font)
        self.pushButton_OpenSaveFolder.setObjectName("pushButton_OpenSaveFolder")
        self.lineEdit_SavePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SavePath.setGeometry(QtCore.QRect(10, 70, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_SavePath.setFont(font)
        self.lineEdit_SavePath.setObjectName("lineEdit_SavePath")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(250, 550, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.spinBox_nV = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_nV.setGeometry(QtCore.QRect(170, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox_nV.setFont(font)
        self.spinBox_nV.setMinimum(2)
        self.spinBox_nV.setMaximum(999)
        self.spinBox_nV.setObjectName("spinBox_nV")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(840, 440, 101, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(170, 160, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_SliceZoomOut = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SliceZoomOut.setGeometry(QtCore.QRect(320, 178, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SliceZoomOut.setFont(font)
        self.pushButton_SliceZoomOut.setObjectName("pushButton_SliceZoomOut")
        self.pushButton_ZoomToFit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ZoomToFit.setGeometry(QtCore.QRect(320, 149, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ZoomToFit.setFont(font)
        self.pushButton_ZoomToFit.setObjectName("pushButton_ZoomToFit")
        self.pushButton_SliceZoomIn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SliceZoomIn.setGeometry(QtCore.QRect(320, 120, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SliceZoomIn.setFont(font)
        self.pushButton_SliceZoomIn.setObjectName("pushButton_SliceZoomIn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 250, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2D = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2D.setFont(font)
        self.radioButton_2D.setChecked(True)
        self.radioButton_2D.setObjectName("radioButton_2D")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_2D)
        self.horizontalLayout.addWidget(self.radioButton_2D)
        self.radioButton_3D = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3D.setFont(font)
        self.radioButton_3D.setObjectName("radioButton_3D")
        self.buttonGroup.addButton(self.radioButton_3D)
        self.horizontalLayout.addWidget(self.radioButton_3D)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 210, 291, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(130, 110, 20, 101))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(300, 110, 20, 191))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registration Tool"))
        self.label_Title.setText(_translate("MainWindow", "Image registration tool v1.3"))
        self.label_Title_2.setText(_translate("MainWindow", "UW BAIL Team"))
        self.label_6.setText(_translate("MainWindow", "Reference image"))
        self.pushButton_LoadStruMov.setText(_translate("MainWindow", "Load Mov"))
        self.pushButton_LoadSeg.setText(_translate("MainWindow", "Apply to Other Images"))
        self.pushButton_LoadFlow_2.setText(_translate("MainWindow", "Apply to Other Images"))
        self.pushButton_LoadStruRef.setText(_translate("MainWindow", "Load Ref"))
        self.label_7.setText(_translate("MainWindow", "Moving image"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run Single"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Single Load"))
        self.label_13.setText(_translate("MainWindow", "Folder Name"))
        self.label_14.setText(_translate("MainWindow", "File Name"))
        self.pushButton_UpdateRule.setText(_translate("MainWindow", "Update Rule"))
        self.lineEdit_FlowPattern.setText(_translate("MainWindow", "projs_flow_0.png"))
        self.lineEdit_StruPattern.setText(_translate("MainWindow", "Flow"))
        self.pushButton_RunSingle.setText(_translate("MainWindow", "Run Single"))
        self.pushButton_RunBatch.setText(_translate("MainWindow", "Run Batch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Batch Load"))
        self.lineEdit_OpenPath.setText(_translate("MainWindow", "Input open path"))
        self.pushButton_BatchOpen.setText(_translate("MainWindow", "Open Folder"))
        __sortingEnabled = self.listWidget_ParaInfo.isSortingEnabled()
        self.listWidget_ParaInfo.setSortingEnabled(False)
        item = self.listWidget_ParaInfo.item(0)
        item.setText(_translate("MainWindow", "Pre-load parameters"))
        item = self.listWidget_ParaInfo.item(1)
        item.setText(_translate("MainWindow", "2D"))
        item = self.listWidget_ParaInfo.item(2)
        item.setText(_translate("MainWindow", "Translate: "))
        item = self.listWidget_ParaInfo.item(3)
        item.setText(_translate("MainWindow", "Affine: paramters 12"))
        item = self.listWidget_ParaInfo.item(4)
        item.setText(_translate("MainWindow", "Bspine: "))
        item = self.listWidget_ParaInfo.item(5)
        item.setText(_translate("MainWindow", "Optimizer: ASGD"))
        item = self.listWidget_ParaInfo.item(6)
        item.setText(_translate("MainWindow", "Metrics: Mutual Information"))
        item = self.listWidget_ParaInfo.item(7)
        item.setText(_translate("MainWindow", "Processer: CPU"))
        self.listWidget_ParaInfo.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Type of registration"))
        self.plainTextEdit_log.setPlainText(_translate("MainWindow", "Logs:"))
        self.label_2.setText(_translate("MainWindow", "Ref Img"))
        self.label_3.setText(_translate("MainWindow", "Mov Img"))
        self.label_4.setText(_translate("MainWindow", "Averaged"))
        self.label_5.setText(_translate("MainWindow", "Image Group"))
        self.checkBox.setText(_translate("MainWindow", "Tranlate"))
        self.checkBox_2.setText(_translate("MainWindow", "Affine"))
        self.checkBox_3.setText(_translate("MainWindow", "Bspine"))
        self.label_9.setText(_translate("MainWindow", "Image type"))
        self.radioButton_SingleFile.setText(_translate("MainWindow", "Single file "))
        self.radioButton_MultiFile.setText(_translate("MainWindow", "Multi file "))
        self.label_10.setText(_translate("MainWindow", "File Type"))
        self.pushButton_OpenSaveFolder.setText(_translate("MainWindow", "Open Save Folder"))
        self.lineEdit_SavePath.setText(_translate("MainWindow", "Input save path here"))
        self.pushButton.setText(_translate("MainWindow", "Check Loss"))
        self.label_11.setText(_translate("MainWindow", "Residual Errors"))
        self.label_12.setText(_translate("MainWindow", "Number of dataset"))
        self.pushButton_SliceZoomOut.setText(_translate("MainWindow", "- ZoomOut"))
        self.pushButton_ZoomToFit.setText(_translate("MainWindow", "Fit"))
        self.pushButton_SliceZoomIn.setText(_translate("MainWindow", "+ ZoomIn"))
        self.radioButton_2D.setText(_translate("MainWindow", "2D"))
        self.radioButton_3D.setText(_translate("MainWindow", "3D"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
