# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tail.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1535, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_XY = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_XY.setGeometry(QtCore.QRect(50, 30, 341, 341))
        self.graphicsView_XY.setObjectName("graphicsView_XY")
        self.graphicsView_YZ = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_YZ.setGeometry(QtCore.QRect(50, 400, 341, 341))
        self.graphicsView_YZ.setObjectName("graphicsView_YZ")
        self.graphicsView_XZ = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_XZ.setGeometry(QtCore.QRect(430, 30, 341, 341))
        self.graphicsView_XZ.setObjectName("graphicsView_XZ")
        self.lineEdit_XLow = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_XLow.setEnabled(True)
        self.lineEdit_XLow.setGeometry(QtCore.QRect(570, 460, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_XLow.setFont(font)
        self.lineEdit_XLow.setObjectName("lineEdit_XLow")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 400, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_XHigh = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_XHigh.setEnabled(True)
        self.lineEdit_XHigh.setGeometry(QtCore.QRect(660, 460, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_XHigh.setFont(font)
        self.lineEdit_XHigh.setObjectName("lineEdit_XHigh")
        self.lineEdit_YHigh = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_YHigh.setEnabled(True)
        self.lineEdit_YHigh.setGeometry(QtCore.QRect(660, 500, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_YHigh.setFont(font)
        self.lineEdit_YHigh.setObjectName("lineEdit_YHigh")
        self.lineEdit_YLow = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_YLow.setEnabled(True)
        self.lineEdit_YLow.setGeometry(QtCore.QRect(570, 500, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_YLow.setFont(font)
        self.lineEdit_YLow.setObjectName("lineEdit_YLow")
        self.lineEdit_ZLow = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ZLow.setEnabled(True)
        self.lineEdit_ZLow.setGeometry(QtCore.QRect(570, 540, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ZLow.setFont(font)
        self.lineEdit_ZLow.setObjectName("lineEdit_ZLow")
        self.lineEdit_ZHigh = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ZHigh.setEnabled(True)
        self.lineEdit_ZHigh.setGeometry(QtCore.QRect(660, 540, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ZHigh.setFont(font)
        self.lineEdit_ZHigh.setObjectName("lineEdit_ZHigh")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 460, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 500, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 540, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(820, 390, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_Preview = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Preview.setGeometry(QtCore.QRect(820, 600, 271, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Preview.setFont(font)
        self.pushButton_Preview.setObjectName("pushButton_Preview")
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setGeometry(QtCore.QRect(820, 650, 271, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, -10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, -10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_Amp = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Amp.setEnabled(True)
        self.lineEdit_Amp.setGeometry(QtCore.QRect(900, 440, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Amp.setFont(font)
        self.lineEdit_Amp.setObjectName("lineEdit_Amp")
        self.lineEdit_Dec = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Dec.setEnabled(True)
        self.lineEdit_Dec.setGeometry(QtCore.QRect(900, 470, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Dec.setFont(font)
        self.lineEdit_Dec.setObjectName("lineEdit_Dec")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(820, 440, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(820, 470, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.graphicsView_TailRec = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_TailRec.setGeometry(QtCore.QRect(1130, 420, 391, 351))
        self.graphicsView_TailRec.setObjectName("graphicsView_TailRec")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(820, 500, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.graphicsView_TailOri = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_TailOri.setGeometry(QtCore.QRect(1130, 40, 391, 351))
        self.graphicsView_TailOri.setObjectName("graphicsView_TailOri")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 360, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(380, 10, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(760, 10, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(420, 350, 47, 13))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 720, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(380, 380, 47, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(420, 1110, 47, 13))
        self.label_18.setObjectName("label_18")
        self.pushButton_Update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Update.setGeometry(QtCore.QRect(500, 580, 221, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Update.setFont(font)
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.spinBox_Slice = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Slice.setGeometry(QtCore.QRect(500, 690, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBox_Slice.setFont(font)
        self.spinBox_Slice.setMaximum(9999)
        self.spinBox_Slice.setObjectName("spinBox_Slice")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(500, 660, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_BitDepth = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_BitDepth.setEnabled(True)
        self.lineEdit_BitDepth.setGeometry(QtCore.QRect(900, 500, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_BitDepth.setFont(font)
        self.lineEdit_BitDepth.setObjectName("lineEdit_BitDepth")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(580, 440, 47, 13))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(660, 440, 47, 13))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1280, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(1280, 400, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_OpenPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OpenPath.setGeometry(QtCore.QRect(810, 10, 211, 21))
        self.lineEdit_OpenPath.setText("")
        self.lineEdit_OpenPath.setObjectName("lineEdit_OpenPath")
        self.pushButton_BatchOpen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_BatchOpen.setGeometry(QtCore.QRect(1030, 10, 76, 23))
        self.pushButton_BatchOpen.setObjectName("pushButton_BatchOpen")
        self.lineEdit_StruPattern = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_StruPattern.setGeometry(QtCore.QRect(880, 100, 98, 20))
        self.lineEdit_StruPattern.setObjectName("lineEdit_StruPattern")
        self.listWidget_BatchList = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_BatchList.setGeometry(QtCore.QRect(810, 210, 291, 161))
        self.listWidget_BatchList.setObjectName("listWidget_BatchList")
        self.pushButton_RunSingle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RunSingle.setEnabled(True)
        self.pushButton_RunSingle.setGeometry(QtCore.QRect(820, 690, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RunSingle.setFont(font)
        self.pushButton_RunSingle.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_RunSingle.setObjectName("pushButton_RunSingle")
        self.pushButton_RunBatch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RunBatch.setEnabled(True)
        self.pushButton_RunBatch.setGeometry(QtCore.QRect(970, 690, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RunBatch.setFont(font)
        self.pushButton_RunBatch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_RunBatch.setMouseTracking(False)
        self.pushButton_RunBatch.setWhatsThis("")
        self.pushButton_RunBatch.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton_RunBatch.setObjectName("pushButton_RunBatch")
        self.lineEdit_FolderPattern = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FolderPattern.setGeometry(QtCore.QRect(880, 70, 98, 20))
        self.lineEdit_FolderPattern.setObjectName("lineEdit_FolderPattern")
        self.lineEdit_FlowPattern = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FlowPattern.setGeometry(QtCore.QRect(880, 130, 98, 20))
        self.lineEdit_FlowPattern.setObjectName("lineEdit_FlowPattern")
        self.pushButton_LoadSingle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LoadSingle.setEnabled(True)
        self.pushButton_LoadSingle.setGeometry(QtCore.QRect(820, 170, 271, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_LoadSingle.setFont(font)
        self.pushButton_LoadSingle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_LoadSingle.setObjectName("pushButton_LoadSingle")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(820, 40, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(820, 70, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(820, 100, 47, 13))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(820, 130, 47, 13))
        self.label_27.setObjectName("label_27")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(760, 390, 20, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(810, 380, 301, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_Rg_L = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Rg_L.setEnabled(True)
        self.lineEdit_Rg_L.setGeometry(QtCore.QRect(900, 530, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Rg_L.setFont(font)
        self.lineEdit_Rg_L.setObjectName("lineEdit_Rg_L")
        self.lineEdit_Rg_H = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Rg_H.setEnabled(True)
        self.lineEdit_Rg_H.setGeometry(QtCore.QRect(900, 560, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Rg_H.setFont(font)
        self.lineEdit_Rg_H.setObjectName("lineEdit_Rg_H")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(790, 530, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(790, 560, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1010, 530, 41, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1010, 560, 41, 20))
        self.label_31.setObjectName("label_31")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1535, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tail Removal Tool"))
        self.lineEdit_XLow.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Trim image"))
        self.lineEdit_XHigh.setText(_translate("MainWindow", "10000"))
        self.lineEdit_YHigh.setText(_translate("MainWindow", "10000"))
        self.lineEdit_YLow.setText(_translate("MainWindow", "0"))
        self.lineEdit_ZLow.setText(_translate("MainWindow", "0"))
        self.lineEdit_ZHigh.setText(_translate("MainWindow", "10000"))
        self.label_2.setText(_translate("MainWindow", "X range"))
        self.label_3.setText(_translate("MainWindow", "Y range"))
        self.label_4.setText(_translate("MainWindow", "Z range"))
        self.label_5.setText(_translate("MainWindow", "Algorithm Parameters"))
        self.pushButton_Preview.setText(_translate("MainWindow", "Preview"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save Parameters"))
        self.label_6.setText(_translate("MainWindow", "Enface (X-Y)"))
        self.label_7.setText(_translate("MainWindow", "Slow (Y-Z)"))
        self.label_8.setText(_translate("MainWindow", "Fast (X-Z)"))
        self.lineEdit_Amp.setText(_translate("MainWindow", "0.07"))
        self.lineEdit_Dec.setText(_translate("MainWindow", "0.012"))
        self.label_9.setText(_translate("MainWindow", "Amplitude "))
        self.label_10.setText(_translate("MainWindow", "Decrease "))
        self.label_11.setText(_translate("MainWindow", "BitDepth"))
        self.label_12.setText(_translate("MainWindow", "X"))
        self.label_13.setText(_translate("MainWindow", "Y"))
        self.label_14.setText(_translate("MainWindow", "X"))
        self.label_15.setText(_translate("MainWindow", "Z"))
        self.label_16.setText(_translate("MainWindow", "Z"))
        self.label_17.setText(_translate("MainWindow", "Y"))
        self.label_18.setText(_translate("MainWindow", "Z"))
        self.pushButton_Update.setText(_translate("MainWindow", "Update Boundry"))
        self.label_19.setText(_translate("MainWindow", "SliceNum"))
        self.lineEdit_BitDepth.setText(_translate("MainWindow", "16"))
        self.label_20.setText(_translate("MainWindow", "Low"))
        self.label_21.setText(_translate("MainWindow", "High"))
        self.label_22.setText(_translate("MainWindow", "Original Flow"))
        self.label_23.setText(_translate("MainWindow", "Tail Free Slice"))
        self.pushButton_BatchOpen.setText(_translate("MainWindow", "Open Folder"))
        self.lineEdit_StruPattern.setText(_translate("MainWindow", "stru_flatten.dcm"))
        self.pushButton_RunSingle.setText(_translate("MainWindow", "Run Single"))
        self.pushButton_RunBatch.setText(_translate("MainWindow", "Run Batch"))
        self.lineEdit_FolderPattern.setText(_translate("MainWindow", "Flow"))
        self.lineEdit_FlowPattern.setText(_translate("MainWindow", "flow_flatten.dcm"))
        self.pushButton_LoadSingle.setText(_translate("MainWindow", "Load Single File"))
        self.label_24.setText(_translate("MainWindow", "Batch Load Rules:"))
        self.label_25.setText(_translate("MainWindow", "Folder"))
        self.label_26.setText(_translate("MainWindow", "Stru file"))
        self.label_27.setText(_translate("MainWindow", "Flow file"))
        self.lineEdit_Rg_L.setText(_translate("MainWindow", "5"))
        self.lineEdit_Rg_H.setText(_translate("MainWindow", "99.99"))
        self.label_28.setText(_translate("MainWindow", "Output Rg Low"))
        self.label_29.setText(_translate("MainWindow", "Output Rg High"))
        self.label_30.setText(_translate("MainWindow", "%"))
        self.label_31.setText(_translate("MainWindow", "%"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
